name: firelamp_in_app_purchase
description: A new Flutter package project.
publish_to: "none"
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # in_app_purchase: ^0.3.5+1
  in_app_purchase: ^0.5.2
  firelamp:
    path: ../firelamp

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
